### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by mobilex1122** [excaliburjs/excalibur-extension#6]
Will there be firefox version?

**Comment by mobilex1122** [comment]
Found it in the README Sorry for sending this Issue.

**Comment by eonarheim** [comment]
All good! It might work if you try side loading in Firefox since they theoretically support manifest v3, but I haven't attempted yet.

I would definitely support any PRs to fix this

**Comment by eonarheim** [comment]
I gave it a try looks like some effort will be needed, FF doesn't support the same set of features that Chrome does in manifest v3 sadly 

https://github.com/excaliburjs/excalibur-extension/issues/7

**Comment by eonarheim** [comment]
@mobilex1122 I got nerd sniped and figured out how to update the extension! I've submitted a build to the Mozilla Addon Catalog, hopefully we hear back soon. In the mean time I've updated the readme if you'd like to side load the firefox extension

![image](https://github.com/user-attachments/assets/6eab79e3-6eed-4f99-bc3b-d90bd8af09aa)

**Comment by mobilex1122** [comment]
Great! Thank you very much.
